### ISSUE TITLE
Settings/About Button to large

### ISSUE THREAD

**Issue by DominicWrege** [Team-Ladefuchs/parkfuchs#10]
![image](https://github.com/Team-Ladefuchs/parkfuchs/assets/7389000/f6ff7317-790a-4017-98c0-e70ab0a51910)

**Comment by maxxweb** [comment]
Mit Malik gefixt
<img width="314" alt="Bildschirmfoto 2023-09-01 um 11 05 13" src="https://github.com/Team-Ladefuchs/parkfuchs/assets/4647164/e5d72ee4-6eb1-4c11-8138-9279ac07cb54">
