### ISSUE TITLE
Icons überlappen sich

### ISSUE THREAD

**Issue by gitlik** [Team-Ladefuchs/parkfuchs#13]
![image](https://github.com/Team-Ladefuchs/parkfuchs/assets/26041973/b1e8c781-3013-497f-bae4-d95d0a0ffe2b)

**Comment by DominicWrege** [comment]
@maxxweb

**Comment by maxxweb** [comment]
Da liegt der Webview unter dem SwiftView. Könnte man unterschiedlich lösen.
1. X im Webview weglassen
2. Webview etwas nach unten
3. Zahnrad verschieben
Am elgantesten ist natürlich das Zahnrad in der Situation auszublenden. Leider kann ich da m.M.n. keinen Event für abgreifen

**Comment by DominicWrege** [comment]
Habe den Dialog etwas nach unten geschoben https://github.com/Team-Ladefuchs/parkfuchs/commit/e1024425c806dd8638334fd4869159c20b1bc854
