### ISSUE TITLE
https://parkfuchs.app/api/city

### ISSUE THREAD

**Issue by maxxweb** [Team-Ladefuchs/parkfuchs#19]
Die API aktualisiert die privilegierten Standorte nicht. Ich habe vor mehren Tagen Standorte freigegeben und auch zwei obsolete Citys gelöscht (Hamburg Wilhelmsburg, Hamburg Volksdorf ).

**Comment by DominicWrege** [comment]
Was ist den aktuell der Fall ? Werden gelöschte Orte noch ausgeliefert ?

**Comment by DominicWrege** [comment]
fixed https://github.com/Team-Ladefuchs/parkfuchs/commit/9002a0ea6dd1167c2035b11a58dac5f2583811da
