### ISSUE TITLE
Ort, Postleitzahl, oder Location →

### ISSUE THREAD

**Issue by gitlik** [Team-Ladefuchs/parkfuchs#7]
![image](https://github.com/Team-Ladefuchs/parkfuchs/assets/26041973/de85af72-b7ab-4904-9b0d-9ca3ed118eff)

**Comment by DominicWrege** [comment]
Vorschlag: 


1. Ort, Postleitzahl, oder →
2. Ort, Postleitzahl, oder lokale Position →

**Comment by DominicWrege** [comment]
Clear button
<img width="770" alt="image" src="https://github.com/Team-Ladefuchs/parkfuchs/assets/7389000/24b10662-ae81-473f-99fb-093326c78030">

Placeholder
<img width="550" alt="image" src="https://github.com/Team-Ladefuchs/parkfuchs/assets/7389000/2d1b3f7d-1fff-43ab-aa60-707c66d73aa9">

@gitlik @maxxweb

**Comment by DominicWrege** [comment]
<img width="826" alt="image" src="https://github.com/Team-Ladefuchs/parkfuchs/assets/7389000/36f0a50e-fe21-4a31-bbe3-97dbb0d0f0fd">

**Comment by DominicWrege** [comment]
done https://github.com/Team-Ladefuchs/parkfuchs/releases/tag/1.1.1
